// Generated by gencpp from file relaxed_ik_ros1/IKSolution.msg
// DO NOT EDIT!


#ifndef RELAXED_IK_ROS1_MESSAGE_IKSOLUTION_H
#define RELAXED_IK_ROS1_MESSAGE_IKSOLUTION_H

#include <ros/service_traits.h>


#include <relaxed_ik_ros1/IKSolutionRequest.h>
#include <relaxed_ik_ros1/IKSolutionResponse.h>


namespace relaxed_ik_ros1
{

struct IKSolution
{

typedef IKSolutionRequest Request;
typedef IKSolutionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct IKSolution
} // namespace relaxed_ik_ros1


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::relaxed_ik_ros1::IKSolution > {
  static const char* value()
  {
    return "e880646518d0e045f0fd574a26c68ad6";
  }

  static const char* value(const ::relaxed_ik_ros1::IKSolution&) { return value(); }
};

template<>
struct DataType< ::relaxed_ik_ros1::IKSolution > {
  static const char* value()
  {
    return "relaxed_ik_ros1/IKSolution";
  }

  static const char* value(const ::relaxed_ik_ros1::IKSolution&) { return value(); }
};


// service_traits::MD5Sum< ::relaxed_ik_ros1::IKSolutionRequest> should match
// service_traits::MD5Sum< ::relaxed_ik_ros1::IKSolution >
template<>
struct MD5Sum< ::relaxed_ik_ros1::IKSolutionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::relaxed_ik_ros1::IKSolution >::value();
  }
  static const char* value(const ::relaxed_ik_ros1::IKSolutionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::relaxed_ik_ros1::IKSolutionRequest> should match
// service_traits::DataType< ::relaxed_ik_ros1::IKSolution >
template<>
struct DataType< ::relaxed_ik_ros1::IKSolutionRequest>
{
  static const char* value()
  {
    return DataType< ::relaxed_ik_ros1::IKSolution >::value();
  }
  static const char* value(const ::relaxed_ik_ros1::IKSolutionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::relaxed_ik_ros1::IKSolutionResponse> should match
// service_traits::MD5Sum< ::relaxed_ik_ros1::IKSolution >
template<>
struct MD5Sum< ::relaxed_ik_ros1::IKSolutionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::relaxed_ik_ros1::IKSolution >::value();
  }
  static const char* value(const ::relaxed_ik_ros1::IKSolutionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::relaxed_ik_ros1::IKSolutionResponse> should match
// service_traits::DataType< ::relaxed_ik_ros1::IKSolution >
template<>
struct DataType< ::relaxed_ik_ros1::IKSolutionResponse>
{
  static const char* value()
  {
    return DataType< ::relaxed_ik_ros1::IKSolution >::value();
  }
  static const char* value(const ::relaxed_ik_ros1::IKSolutionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RELAXED_IK_ROS1_MESSAGE_IKSOLUTION_H
