(cl:defpackage relaxed_ik_ros1-srv
  (:use )
  (:export
   "IKSOLUTION"
   "<IKSOLUTION-REQUEST>"
   "IKSOLUTION-REQUEST"
   "<IKSOLUTION-RESPONSE>"
   "IKSOLUTION-RESPONSE"
   "RELAXEDIKSOLUTION"
   "<RELAXEDIKSOLUTION-REQUEST>"
   "RELAXEDIKSOLUTION-REQUEST"
   "<RELAXEDIKSOLUTION-RESPONSE>"
   "RELAXEDIKSOLUTION-RESPONSE"
   "RESET"
   "<RESET-REQUEST>"
   "RESET-REQUEST"
   "<RESET-RESPONSE>"
   "RESET-RESPONSE"
   "SELFCOLLISIONQUERY"
   "<SELFCOLLISIONQUERY-REQUEST>"
   "SELFCOLLISIONQUERY-REQUEST"
   "<SELFCOLLISIONQUERY-RESPONSE>"
   "SELFCOLLISIONQUERY-RESPONSE"
  ))

